version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
    image: "webapp:${TAG}"

# start of bind point
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
# end of bind point
  redis:
    image: "redis:alpine"
