version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
      - "8888:8888"
      - protocol: TCP
    image: "wordpress:${TAG}"
# start of bind point
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
# end of bind point
  redis:
    image: "redis:alpine"
